### PR TITLE
 armstub7: Various fixes

### PR DESCRIPTION
**Pull request by AntonioND**
Various fixes to armstub7.

Original message:
> The previous code was enabling both I and D-caches, but keeping the
> bit M as the reset value, which is architecturally undetermined. In
> practice, in both Cortex-A7 and Cortex-A53, the reset value is 0, so
> the D-cache was disabled (but the I-cache was enabled).
> 
> For the 32-bit Arm architecture boot, the Linux kernel expects the data
> cache and MMU to be disabled when the CPU jumps into it, the I-cache
> doesn't matter, as specified in the file `Documentation/arm/Booting` of
> the Linux kernel tree under `Calling the kernel image`.
> 
> This patch disables the D-cache and MMU for correctness while keeping
> the I-cache enabled to save a few cycles during the execution of the
> stub.

Fixes https://github.com/raspberrypi/tools/issues/84

### CODE REVIEW

**Comment by pelwell** [comment]
For other reviewers, see http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0438i/BABJAHDA.html for details of the System Control Register.
That document says that both the D cache and MMU are disabled by default, which would suggest that the correct fix is to remove that line altogether, but since force_core mode relies on an instruction offset I'm happy for this to stay as it is.

@popcornmix?

**Comment by AntonioND** [comment]
While it is true that for A7 and A53 both C and M bits are set to 0 on reset (according to their technical reference manuals), the Arm ARM says (at least, the Armv8 ARM) ``When this register has an architecturally-defined reset value, this field resets to 0.`` so I don't think that explicitly disabling it is a bad idea in case it is needed by future models.

**Comment by AntonioND** [comment]
Relevant links:
Cortex-A7 TRM: http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0464f/BABJAHDA.html
Cortex-A53 TRM: http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0500e/BABJAHDA.html

ARMv8 ARM (no online version, just pdf): https://developer.arm.com/docs/ddi0487/latest/arm-architecture-reference-manual-armv8-for-armv8-a-architecture-profile

**Comment by AntonioND** [comment]
I've added a couple of commits to fix other issues with this bootstrap.

I'm not sure about "armstub7: Remove useless initialization of CNTV_CTL".

**Comment by popcornmix** [comment]
The changes look quite reasonable. Will need double checking on Pi2/Pi3 and force_core firmware code may need patching, but otherwise seems fine.

**Comment by petemoore** [comment]
@popcornmix Is there someone at the Raspberry Pi Foundation that can double check the pi2/pi3? It would be nice to get the PR landed. Many thanks.

**Pull request closed without merging**
